# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160119_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='cat_descripcion',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_description',
            field=models.CharField(default=1, max_length=255, verbose_name='category description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=50, verbose_name='category name'),
        ),
    ]
